GET http://localhost:4000/products

###
POST http://localhost:4000/products
Content-Type: application/json

{
  "name": "Tea",
  "description": "Just tea mate",
  "price": 12.435,
  "sku": "wr2341"
}

###
PUT http://localhost:4000/products/2
Content-Type: application/json

{
  "name": "Espresso with a twist",
  "description": "Short and strong coffee without milk",
  "price": 2.19,
  "sku": "fjd245"
}

